/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_josephbeard_xpdf_PdfToText */

#ifndef _Included_net_josephbeard_xpdf_PdfToText
#define _Included_net_josephbeard_xpdf_PdfToText
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_josephbeard_xpdf_PdfToText
 * Method:    extract
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_josephbeard_xpdf_PdfToText_extract
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
