/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_foolabs_xpdf_GlobalParameters */

#ifndef _Included_com_foolabs_xpdf_GlobalParameters
#define _Included_com_foolabs_xpdf_GlobalParameters
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_foolabs_xpdf_GlobalParameters
 * Method:    _getInstance
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_foolabs_xpdf_GlobalParameters__1getInstance
  (JNIEnv *, jclass);

/*
 * Class:     com_foolabs_xpdf_GlobalParameters
 * Method:    _getTextEncoding
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_foolabs_xpdf_GlobalParameters__1getTextEncoding
  (JNIEnv *, jobject);

/*
 * Class:     com_foolabs_xpdf_GlobalParameters
 * Method:    _setTextEncoding
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_foolabs_xpdf_GlobalParameters__1setTextEncoding
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_foolabs_xpdf_GlobalParameters
 * Method:    _getTextEOL
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_foolabs_xpdf_GlobalParameters__1getTextEOL
  (JNIEnv *, jobject);

/*
 * Class:     com_foolabs_xpdf_GlobalParameters
 * Method:    _setTextEOL
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_foolabs_xpdf_GlobalParameters__1setTextEOL
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_foolabs_xpdf_GlobalParameters
 * Method:    _getTextPageBreaks
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_foolabs_xpdf_GlobalParameters__1getTextPageBreaks
  (JNIEnv *, jobject);

/*
 * Class:     com_foolabs_xpdf_GlobalParameters
 * Method:    _setTextPageBreaks
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_foolabs_xpdf_GlobalParameters__1setTextPageBreaks
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_foolabs_xpdf_GlobalParameters
 * Method:    _getErrQuiet
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_foolabs_xpdf_GlobalParameters__1getErrQuiet
  (JNIEnv *, jobject);

/*
 * Class:     com_foolabs_xpdf_GlobalParameters
 * Method:    _setErrQuiet
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_foolabs_xpdf_GlobalParameters__1setErrQuiet
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_foolabs_xpdf_GlobalParameters
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_foolabs_xpdf_GlobalParameters_finalize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_foolabs_xpdf_GlobalParameters_EndOfLine */

#ifndef _Included_com_foolabs_xpdf_GlobalParameters_EndOfLine
#define _Included_com_foolabs_xpdf_GlobalParameters_EndOfLine
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
