/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_josephbeard_xpdf_PDFPage */

#ifndef _Included_net_josephbeard_xpdf_PDFPage
#define _Included_net_josephbeard_xpdf_PDFPage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_josephbeard_xpdf_PDFPage
 * Method:    _getNumber
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_josephbeard_xpdf_PDFPage__1getNumber
  (JNIEnv *, jobject);

/*
 * Class:     net_josephbeard_xpdf_PDFPage
 * Method:    _getText
 * Signature: (Lnet/josephbeard/xpdf/TextCollector;ZZ)V
 */
JNIEXPORT void JNICALL Java_net_josephbeard_xpdf_PDFPage__1getText
  (JNIEnv *, jobject, jobject, jboolean, jboolean);

/*
 * Class:     net_josephbeard_xpdf_PDFPage
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_josephbeard_xpdf_PDFPage_finalize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
